apiVersion: v2
name: pangolin-gateway
description: Kubernetes controller publishing Gateway API HTTPRoutes as Pangolin resources
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/p3l1/pangolin-gateway
sources:
  - https://github.com/p3l1/pangolin-gateway
keywords:
  - gateway-api
  - pangolin
  - tunnel
  - ingress
